version: '3.8'

services:


  postgres:
    image: postgres:15-alpine
    container_name: music_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: music_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:6.0
    container_name: music_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db
    networks:
      - internal-net

  redis:
    image: redis:7-alpine
    container_name: music_redis
    networks:
      - internal-net

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: music_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - internal-net

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: music_kafka
    depends_on:
      - zookeeper
    networks:
      - internal-net
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


  auth-svc:
    build: ./auth-svc
    container_name: auth-svc
    restart: on-failure
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/music_db
      - REDIS_HOST=redis
      - JWT_SECRET=super_secret_mvp_key
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - internal-net

  content-svc:
    build: ./services/content-svc
    container_name: content-svc
    restart: on-failure
    environment:
      - DB_HOST=postgres
      - MONGO_URL=mongodb://admin:password@mongodb:27017
      - MEDIA_STORAGE_PATH=/media/uploads
    volumes:
      - media_storage:/media/uploads
    depends_on:
      - postgres
      - mongodb
    networks:
      - internal-net

  playlist-svc:
    build: ./services/playlist-svc
    container_name: playlist-svc
    environment:
      - DB_HOST=postgres
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - postgres
      - kafka
    networks:
      - internal-net

  streaming-svc:
    build: ./services/streaming-svc
    container_name: streaming-svc
    restart: always
    environment:
      - REDIS_HOST=redis:6379
      - KAFKA_BROKER=kafka:9092
      - MEDIA_SOURCE_PATH=/media/uploads
    volumes:
      - media_storage:/media/uploads:ro
    depends_on:
      - redis
      - kafka
      - content-svc
    networks:
      - internal-net


  api-gateway:
    image: nginx:alpine
    container_name: api-gateway
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./gateway/certs:/etc/nginx/certs:ro
    depends_on:
      - auth-svc
      - content-svc
      - playlist-svc
      - streaming-svc
    networks:
      - internal-net

volumes:
  postgres_data:
  mongo_data:
  media_storage:

networks:
  internal-net:
    driver: bridge